########################
# based on Ubuntu 18.04
########################

FROM ubuntu:18.04

MAINTAINER Boris Belyaev <belbor1@gmail.com>

RUN apt-get update && apt-get install -y \
      python3-pip python3-dev \
      && pip3 install --upgrade pip \
      && pip3 install virtualenv \
      
WORKDIR jupyter-server

RUN virtualenv jupyter \
      && source jupyter/bin/activate
      
RUN pip install jupyter
